### PR TITLE
fall back locale to partial match

### PR DESCRIPTION
**Pull request by derek-zhou**
In some cases you want to have one general locale to cover multiple cases; ie: one zh locale that cover both zh_CN and zh_TW, one fr to cover both fr_FR and fr_CA.

### CODE REVIEW

**Comment by goofansu** [comment]
@derek-zhou Sorry, I added format check in CI and update this branch to latest, so there are two merge commits. Can you `mix format` and rebase to remove the merge commits? Thanks

**Comment by derek-zhou** [comment]
Done, how about now?

**Comment by derek-zhou** [comment]
let me close this first and do a fresh PR.

**Comment by goofansu** [comment]
Thank you, will check today later.

**Pull request closed without merging**
